services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/nest-js-microservices-445617/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  # =========================
  # AUTH MICROSERVICE
  # =========================
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/nest-js-microservices-445617/image-registry/auth-ms
    environment:
      - PORT=${AUTH_MS_PORT}
      - JWT_SECRET=${AUTH_MS_JWT_SECRET}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}

  # =========================
  # PRODUCTS MICROSERVICE
  # =========================
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/nest-js-microservices-445617/image-registry/products-ms
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # =========================
  # PAYMENTS MICROSERVICE
  # =========================
  payments-ms:
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: southamerica-east1-docker.pkg.dev/nest-js-microservices-445617/image-registry/payments-ms
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET_KEY=${PAYMENTS_MS_STRIPE_SECRET_KEY}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_MS_STRIPE_CANCEL_URL}
      - NATS_SERVERS=nats://nats-server:4222

  # =========================
  # ORDERS MICROSERVICE
  # =========================
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_MS_DB_URL=${ORDERS_MS_DB_URL}
    image: southamerica-east1-docker.pkg.dev/nest-js-microservices-445617/image-registry/orders-ms
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DB_URL}



