apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/nest-js-microservices-445617/image-registry/payments-ms
        name: payments-ms
        env:
          - name: PORT
            value: "3003"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: STRIPE_SUCCESS_URL
            value: 'http://localhost:3000/success'
          - name: STRIPE_CANCEL_URL
            value: 'http://localhost:3000/cancel'
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_secret_key
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_endpoint_secret
        resources: {}
status: {}
